### ISSUE TITLE
Error running diamond: Length sorting reference

### ISSUE THREAD

**Issue by royercj** [eggnogdb/eggnog-mapper#507]
I am running emapper.py on a cluster, and I tried to run a test on one .faa. I have exported the data dir to EGGNOG_DATA_DIR="/storage/scratch/eggnog_db". I ran the test using the following command (some path names truncated):

`emapper.py  --data_dir $EGGNOG_DATA_DIR 
-i faa/GCA_00342195.faa 
--itype proteins 
--cpu 4 --override 
--pident 70 --query_cover 70 
--output $(basename GCA_00342195.faa .faa)  --output_dir scratch/eggnog/ 
--scratch_dir scratch/eggnog/ --temp_dir scratch/eggnog/ `

This results in the following output with error message:

```
#  emapper-2.1.12
# emapper.py  --data_dir /storage/scratch/eggnog_db  -i faa/GCA_00342195.faa --itype proteins --cpu 4 --override --pident 70 --query_cover 70 --output GCA_00342195 --output_dir scratch/eggnog/ --scratch_dir scratch/eggnog/ --temp_dir scratch/eggnog/
 
envs/eggnog/bin/diamond blastp -d 'scratch/eggnog_db/eggnog_proteins.dmnd' -q '/storage/scratch/faa/GCA_00342195.faa' --threads 4 -o 'eggnog/GCA_00342195.emapper.hits' --tmpdir 'scratch/eggnog/emappertmp_dmdn_7r_et45u' --sensitive --iterate -e 0.001 --id 70.0 --query-cover 70.0 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp

Error running diamond: Length sorting reference...
```
I did not see this error mentioned before, so any help I could get would be greatly appreciated. Thanks!

**Comment by Cantalapiedra** [comment]
Dear @royercj ,

How did you install eggnog-mapper?
Which is the version of diamond that its being run?

Best,
Carlos

**Comment by royercj** [comment]
Hi Carlos, thanks for the reply. I created a conda env to run eggnog, and installed it with `conda install bioconda::eggnog-mapper` (version 2.1.12). Diamond 2.1.9 was installed in this env, as was python 3.12.3.

**Comment by Cantalapiedra** [comment]
Hi @royercj ,

Thank you for your follow up. Do you have any other diamond version installed? What is the output of
`which diamond`
`diamond --version`
?

**Comment by royercj** [comment]
The results of `which diamond` just shows the env path (~/envs/eggnog/bin/diamond) and `diamond --version` returns 2.1.9.

**Comment by Cantalapiedra** [comment]
OK. No clue there. Could you please try running the diamond command from your first post alone, without eggnog-mapper?
Just to see if it gives us any other clue.

`envs/eggnog/bin/diamond blastp -d 'scratch/eggnog_db/eggnog_proteins.dmnd' -q '/storage/scratch/faa/GCA_00342195.faa' --threads 4 -o 'eggnog/GCA_00342195.emapper.hits' --tmpdir 'scratch/eggnog/emappertmp_dmdn_7r_et45u' --sensitive --iterate -e 0.001 --id 70.0 --query-cover 70.0 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp`

**Comment by royercj** [comment]
@Cantalapiedra I was able to run the command you gave me, and everything appeared to run normally. I did not get any error messages and I got the output file I expected.

**Comment by Cantalapiedra** [comment]
@royercj ,

Oh, it is a bit weird that diamond now was working fine. Maybe the first error was a one-time thing? 
Did you try to run the same eggnog-mapper command more than once?

**Comment by ThorstenHansen** [comment]
@Cantalapiedra Hello, I actually ran into this error today while trying to run eggNOG mapper. It might actually be a error connected to the 2.1.9 version of DIAMOND (https://github.com/bbuchfink/diamond/issues/785) and it might get fixed in the 2.1.10 release. Once I downgraded to DIAMOND 2.1.8 eggNOG mapper worked completely fine. Hope this helps.

**Comment by royercj** [comment]
Thanks for the info on this! I forgot to follow up in May, but when I returned to work on the cluster a couple of days after the error appeared, eggnog ran normally. I'm not sure why it corrected itself, but thanks for looking into the issue and I'll be sure to use DIAMOND 2.1.8 if it appears again.

**Comment by mdhishamshaikh** [comment]
Hi, so I have ran into the same issue `Error running diamond: Length sorting reference...`  when running eggnog-mapper on a test proteins fasta (25 proteins) to ensure everything is well before I submit it as a job. I am working on a HPC cluster. The issue didn't resolve even after downgrading diamond to 2.1.8. But, when i submitted the same job, it works fine. I could annotate my hits table too. I'm assuming this is a memory issue on interactive HPC servers...
